  CREATE TABLE SELLER
   (	IDSELLER NUMBER(5,0), 
	SELLERNAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	RATING NUMBER(1,0), 
	STREET VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	CITY VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	STATE VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	ZIPCODE NUMBER(5,0) NOT NULL ENABLE, 
	 PRIMARY KEY (IDSELLER)
);

     CREATE TABLE PRODUCT 
   (IDPRODUCT NUMBER(5,0), 
	PRODUCTNAME VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	SHORTDESCRIPTION VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	LONGDESCRIPTION VARCHAR2(1000 BYTE), 
	PRICE NUMBER(6,0) NOT NULL ENABLE, 
	BESTSELLING VARCHAR2(1 BYTE), 
	AVAILABILITY NUMBER(4,0) NOT NULL ENABLE, 
	IMAGE VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	IDSELLER NUMBER(5,0) NOT NULL ENABLE, 
	 PRIMARY KEY (IDPRODUCT),
  	 CONSTRAINT IDSELLER_FK FOREIGN KEY (IDSELLER)
	  REFERENCES SELLER (IDSELLER) ON DELETE CASCADE ENABLE
   );
     CREATE TABLE CUSTOMERINFO
   (IDCUSTOMER NUMBER(5,0), 
	EMAILADDRESS VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	PASSWORD VARCHAR2(15 BYTE), 
	FIRSTNAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	LASTNAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PHONE1 NUMBER(10,0), 
	PHONE2 NUMBER(10,0), 
	 PRIMARY KEY (IDCUSTOMER)
     );
	 
CREATE TABLE QUESTIONS
   (	IDQUESTION NUMBER(5,0), 
	QUESTION VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	IDCUSTOMER NUMBER(5,0) NOT NULL ENABLE, 
	 PRIMARY KEY (IDQUESTION),
	 CONSTRAINT IDCUSTOMER_FK FOREIGN KEY (IDCUSTOMER)
	  REFERENCES CUSTOMERINFO (IDCUSTOMER) ON DELETE CASCADE ENABLE
   );
   
  CREATE TABLE GIFTCARD
   (	CARDNUMBER NUMBER(16,0), 
	BALANCE NUMBER(5,0), 
	 PRIMARY KEY (CARDNUMBER)
   );
   
 
  CREATE TABLE OFFERS
   (	IDOFFER NUMBER(5,0), 
	DISCOUNTRATE NUMBER(6,0) NOT NULL ENABLE, 
	EXPIRYDATE DATE, 
	IDPRODUCT NUMBER(5,0) NOT NULL ENABLE, 
	 PRIMARY KEY (IDOFFER),
   CONSTRAINT PROD_FK FOREIGN KEY (IDPRODUCT)
	  REFERENCES PRODUCT (IDPRODUCT) ON DELETE CASCADE ENABLE
   );

    CREATE TABLE QUESTIONS
   (IDQUESTION NUMBER(5,0), 
	QUESTION VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	IDCUSTOMER NUMBER(5,0) NOT NULL ENABLE, 
	PRIMARY KEY (IDQUESTION),
   	 CONSTRAINT IDCUSTOMER_FK FOREIGN KEY (IDCUSTOMER)
	  REFERENCES CUSTOMERINFO (IDCUSTOMER) ON DELETE CASCADE ENABLE
   );
      
  
  CREATE TABLE ANSWER
   (	IDANSWER NUMBER(5,0), 
	IDQUESTION NUMBER(5,0) NOT NULL ENABLE, 
	ANSWER VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	IDSELLER NUMBER(5,0) NOT NULL ENABLE, 
	 PRIMARY KEY (IDANSWER),
	 CONSTRAINT QUESTION_FK FOREIGN KEY (IDQUESTION)
	  REFERENCES QUESTIONS (IDQUESTION) ON DELETE CASCADE ENABLE, 
	 CONSTRAINT SELLER_FK FOREIGN KEY (IDSELLER)
	  REFERENCES SELLER (IDSELLER) ON DELETE CASCADE ENABLE
   );
   
   
    CREATE TABLE REVIEW 
   (IDREVIEW NUMBER(5,0), 
	REVIEWERNAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	RATING NUMBER(1,0) NOT NULL ENABLE, 
	CUSTOMERCOMMENT VARCHAR2(300 BYTE), 
	IDPRODUCT NUMBER(5,0) NOT NULL ENABLE, 
	 PRIMARY KEY (IDREVIEW),
	 CONSTRAINT IDPRODUCT_FK FOREIGN KEY (IDPRODUCT)
	  REFERENCES PRODUCT (IDPRODUCT) ON DELETE CASCADE ENABLE
   );
   

	   CREATE TABLE ADDRESS
   (IDADDRESS NUMBER(5,0), 
	STREET VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	CITY VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	STATE VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	ZIPCODE NUMBER(5,0) NOT NULL ENABLE, 
	ADDRESSTYPE VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	DEFAULTADDRESS VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	IDCUSTOMER NUMBER(5,0), 
	 PRIMARY KEY (IDADDRESS),
	 CONSTRAINT FK_CUSTOMER FOREIGN KEY (IDCUSTOMER)
	  REFERENCES CUSTOMERINFO (IDCUSTOMER) ENABLE
   ) ;
   
     CREATE TABLE CREDITCARDINFO
   (CARDTYPE VARCHAR2(30 BYTE), 
	CARDNUMBER NUMBER(16,0) NOT NULL ENABLE, 
	CVV NUMBER(3,0) NOT NULL ENABLE, 
	NAMEONCARD VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	MONTH VARCHAR2(4 BYTE), 
	YEAR NUMBER(4,0), 
	IDCUSTOMER NUMBER(5,0), 
	 CONSTRAINT PK_CCARD PRIMARY KEY (CARDNUMBER),
	 CONSTRAINT FK_CUSTOMER2 FOREIGN KEY (IDCUSTOMER)
	  REFERENCES CUSTOMERINFO (IDCUSTOMER) ENABLE
     );

    CREATE TABLE PRODUCTSIZE
   (IDPRODUCTSIZE NUMBER(5,0), 
	IDPRODUCT NUMBER(5,0) NOT NULL ENABLE, 
	PRODUCTSIZE VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	QUANTITYAVAILABLE NUMBER(3,0), 
	 CONSTRAINT PRODUCTSIZEID PRIMARY KEY (IDPRODUCTSIZE),
  	 CONSTRAINT PRODUCTS_FK FOREIGN KEY (IDPRODUCT)
	  REFERENCES PRODUCT (IDPRODUCT) ON DELETE CASCADE ENABLE
   );

	 
	   CREATE TABLE PRODUCTDETAIL
   (IDDETAILS NUMBER(5,0), 
	DIMENSIONS VARCHAR2(30 BYTE), 
	ACTUALWEIGHT NUMBER(3,0) NOT NULL ENABLE, 
	FLAVOURS VARCHAR2(30 BYTE), 
	SHIPPINGWEIGHT NUMBER(3,0) NOT NULL ENABLE, 
	IDPRODUCTSIZE NUMBER(5,0) NOT NULL ENABLE, 
	 PRIMARY KEY (IDDETAILS),
   CONSTRAINT PRODUCTSIZE_FK FOREIGN KEY (IDPRODUCTSIZE)
	  REFERENCES PRODUCTSIZE (IDPRODUCTSIZE) ON DELETE CASCADE ENABLE
   );

   
     CREATE TABLE ORDERHISTORY 
   (	IDORDER NUMBER(5,0), 
	ORDERNUM NUMBER(5,0) NOT NULL ENABLE, 
	ORDERDATE DATE NOT NULL ENABLE, 
	IDADDRESS NUMBER(5,0) NOT NULL ENABLE, 
	IDCUSTOMER NUMBER(5,0), 
	 PRIMARY KEY (IDORDER),
	 CONSTRAINT ADDRESS_FK FOREIGN KEY (IDADDRESS)
	  REFERENCES ADDRESS (IDADDRESS) ON DELETE CASCADE ENABLE, 
	 CONSTRAINT FK_CUST_ORDERHISTORY FOREIGN KEY (IDCUSTOMER)
	  REFERENCES CUSTOMERINFO (IDCUSTOMER) ENABLE
   );

  
    CREATE TABLE CART 
   (	IDCART NUMBER(5,0), 
	QUANTITY NUMBER(3,0), 
	IDCUSTOMER NUMBER(5,0) NOT NULL ENABLE, 
	IDPRODUCT NUMBER(5,0) NOT NULL ENABLE, 
	 PRIMARY KEY (IDCART),
	 CONSTRAINT CUSTOMERINF_FK FOREIGN KEY (IDCUSTOMER)
	  REFERENCES CUSTOMERINFO (IDCUSTOMER) ON DELETE CASCADE ENABLE, 
	 CONSTRAINT PRODUCTINFO_FK FOREIGN KEY (IDPRODUCT)
	  REFERENCES PRODUCT (IDPRODUCT) ON DELETE CASCADE ENABLE
   );
  
  
	 CREATE TABLE ORDERHISTORY 
   (	IDORDER NUMBER(5,0), 
	ORDERNUM NUMBER(5,0) NOT NULL ENABLE, 
	ORDERDATE DATE NOT NULL ENABLE, 
	IDADDRESS NUMBER(5,0) NOT NULL ENABLE, 
	IDCUSTOMER NUMBER(5,0), 
	 PRIMARY KEY (IDORDER),
	 CONSTRAINT ADDRESS_FK FOREIGN KEY (IDADDRESS)
	  REFERENCES ADDRESS (IDADDRESS) ON DELETE CASCADE ENABLE, 
	 CONSTRAINT FK_CUST_ORDERHISTORY FOREIGN KEY (IDCUSTOMER)
	  REFERENCES CUSTOMERINFO (IDCUSTOMER) ENABLE
   );

   CREATE TABLE ORDEREDPRODUCT
   (IDORDER NUMBER(5,0), 
	IDPRODUCT NUMBER(5,0), 
	GIFT VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	PRICE NUMBER(6,0) NOT NULL ENABLE, 
	PRICEPLUSTAX NUMBER(6,0) NOT NULL ENABLE, 
	DELIVERYDATE DATE NOT NULL ENABLE, 
	STATUS VARCHAR2(20 BYTE) DEFAULT 'Shipped', 
	QUANTITY NUMBER(3,0), 
	 CONSTRAINT ORDEREDPRODUCTID PRIMARY KEY (IDORDER, IDPRODUCT),
 	 CONSTRAINT ORDERED_FK FOREIGN KEY (IDORDER)
	  REFERENCES ORDERHISTORY (IDORDER) ON DELETE CASCADE ENABLE, 
	 CONSTRAINT PRO_FK FOREIGN KEY (IDPRODUCT)
	  REFERENCES PRODUCT (IDPRODUCT) ON DELETE CASCADE ENABLE
   );